# -*- coding: utf-8 -*-
"""python part 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SyeDLmVuV9wGDeOPGcYmYlmaW7maHfH0

# Memahami alur kerja datascience
"""

!pip install pandas

import numpy
array_1 = numpy.array([1,2,3]) #konstruksi array  dengan memasukkan list kedalama argumen numpy.array

import numpy as np
array_1 = numpy.array([1,2,3])

from numpy import array
array_1 = numpy.array([1,2,3])

data = np.array([1, 2, 3])
data.ndim
#1 dimensi karena hanya 1 baris atau panjang doang

data = np.array([[1,2,3],
                 [2,3,4]],)
print("ndim =", data.ndim)
print("shape =", data.shape)
print("dtype =", data.dtype)
#data 2 dimensi
#karena memiliki 1 kolom dan 1 baris atau panjang dan lebar

"""## 2.1indexing and slicing

indexing dan slicing pada numpy array
"""

#membuat random matrix 4x4
random_matrix = np.random.random((4,4))
random_matrix

np.diag(random_matrix)

#ambil index 2,3 (ingat indext mulai dari 0)
random_matrix[2][3]

#slice baris ke 1~3 dan kolom 2~3 (index mulai dari 0,dan range exclusive angka sebelah kanan)
random_matrix[1:3, 2:3]

"""## 2.2 operasi numerik"""

mat = np.random.randint(0,10, (2,3))
mat

#transpose
mat.T

# dot product
mat.dot(mat.T)

#jika tidak tau maka beri tanda ? dipaling kiri
?np.random.random_integers

import cv2
from google.colab.patches import cv2_imshow
img = cv2.imread("soal1.jpg")
cv2_imshow(img)

A = np.array(
    [[1,3],
    [3,1]]
)

b = np.array([5,2])
v= np.linalg.inv(A).dot(b)
print("maka nilai (x,y) adalah", tuple(v))

x,y = tuple (v)
print("persamaan 1 cek: x + 3y=", x + 3*y)
print("persamaan 2 cek: 3x + y=", 3*y + y)

"""# Pengenalan Pandas

toolbox data analisis,karena memiliki fungsi manipulasi data table, visualisasi dasar, statistik deskriptif,dll
"""

import pandas as pd
import numpy as np
# agar bisa pakai google drive sebagai tempat penyimpanan data
from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd
df = pd.read_csv("./Iris.csv")

import pandas as pd
df = pd.read_csv("./Iris.csv")
df.head(10)
#menampilkan 10 data awal

#membaca 10 data terakhir
df.tail(10)

# Mengambil baris dari indeks 10 hingga 19
slicing = df[10:20]  # Mengambil baris 10 hingga 19
print(slicing)

"""## pandas atribute"""

#nama columns
df.columns

#data types
df.dtypes

#data shapes
df.shape

# index
print(df.index)
# kenapa index berbeda?
#karena disimpan dalam data range index dari pandasnya

#values pandas sebagai array
df.values

#statistik deskripsi untuk tiap kolom
df.describe()

"""### df.method
 fungsi yang bekerja terhadap objek terhadap data frame harus pakai ()
"""

# rangkuman dataframe
df.info()

df.dropna

"""### Data farme slicing"""

# ambil hanya kolom spesifik
df_slice = df[['SepalLengthCm', "SepalWidthCm"]]
df_slice.head()

# penggunaan loc, nilai sebelah kanan inclusive
df_slice = df.loc[:, 'SepalLengthCm':'PetalLengthCm']
df_slice.head()

# penggunan iloc, nilai sebelah kanan
df_slice = df.iloc[:, 1:3]
df_slice.head()

